name: cloud_connect_repository
description: Dart package which manages the firebase funtion.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:

  authentication_repository:
    path: ../authentication_repository
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  cloud_functions: ^5.1.3
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  test: ^1.16.4
