name: ai_analyzer_repository
      
description: Dart package which manages the AI funtion.
version: 1.0.0
publish_to: none
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.10.1
  image: ^4.0.17
  google_ml_kit: ^0.19.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  test: ^1.16.4


  