// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrTgCSYYOdCfxTnItF4PXhf2FmJu4cXr4',
    appId: '1:1055955458186:web:e748b7f98bd57179307573',
    messagingSenderId: '1055955458186',
    projectId: 'kommeet',
    authDomain: 'kommeet.firebaseapp.com',
    storageBucket: 'kommeet.appspot.com',
    measurementId: 'G-LWQMM3RTDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-peC4agkC6KVOymQCoJuPAB3ii0bhtFU',
    appId: '1:1055955458186:android:7d2713d03961f289307573',
    messagingSenderId: '1055955458186',
    projectId: 'kommeet',
    storageBucket: 'kommeet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMt7nSTMA8sdwBFXNrFQVqx4IhdfwDj2c',
    appId: '1:1055955458186:ios:e9ce79a2e30eab03307573',
    messagingSenderId: '1055955458186',
    projectId: 'kommeet',
    storageBucket: 'kommeet.appspot.com',
    iosBundleId: 'ai.sohyah.dating.sohyah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMt7nSTMA8sdwBFXNrFQVqx4IhdfwDj2c',
    appId: '1:1055955458186:ios:e9ce79a2e30eab03307573',
    messagingSenderId: '1055955458186',
    projectId: 'kommeet',
    storageBucket: 'kommeet.appspot.com',
    iosBundleId: 'ai.sohyah.dating.sohyah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrTgCSYYOdCfxTnItF4PXhf2FmJu4cXr4',
    appId: '1:1055955458186:web:037c64e9219194ef307573',
    messagingSenderId: '1055955458186',
    projectId: 'kommeet',
    authDomain: 'kommeet.firebaseapp.com',
    storageBucket: 'kommeet.appspot.com',
    measurementId: 'G-Z0Z9Q6Q3J1',
  );

}